// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgInfo.proto

package com.pgsainia.domain;

public interface MsgBodyOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.pgsainia.domain.MsgBody)
        com.google.protobuf.MessageOrBuilder {


    String getChannelId();

    com.google.protobuf.ByteString
    getChannelIdBytes();


    String getMsgInfo();

    com.google.protobuf.ByteString
    getMsgInfoBytes();
}
